/**
 * Consents tab — lists surgical consents linked to this admission,
 * with a quick "New" button that navigates to the consent creation
 * route with the patient/admission context pre-filled.
 *
 * Jun-16: added per-row DELETE button. The clinical staff often
 * generates a consent against the wrong patient / wrong procedure
 * during the OPD-rush ward round; instead of leaving an orphaned
 * record on the chart they can now soft-delete it (the backend uses
 * `deleted_at` so the audit trail is preserved — see
 * `/api/surgical-consents/{cid}` DELETE in `routers/surgical_consents.py`).
 * The action is a destructive Alert.alert with explicit confirmation
 * to prevent fat-finger deletions during ward rounds.
 */
import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import api from '../../api';
import { useToast } from '../../toast';
import { confirmAction } from '../../cross-alert';
import { COLORS } from '../../theme';
import { formatISTShort } from '../../date';
import { ipdStyles as styles } from '../styles';
import type { Admission } from '../types';

export default function ConsentsTab({
  admission, admissionId, isDischarged, consents, setConsents, onClose,
}: {
  admission: Admission;
  admissionId: string;
  isDischarged: boolean;
  consents: any[];
  setConsents: React.Dispatch<React.SetStateAction<any[]>>;
  onClose: () => void;
}) {
  const router = useRouter();
  const toast = useToast();
  const a = admission;
  // Track which consent_id is currently being deleted so we can
  // disable the row + show a spinner in place of the trash icon.
  // The parent's `consents` list is the source of truth — we just
  // splice the deleted row out optimistically after a successful
  // DELETE call.
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const onDelete = (c: any) => {
    if (deletingId) return;
    const title =
      c.procedure_snapshot?.name?.en
      || (c.procedure_snapshots?.[0]?.name?.en)
      || c.procedure_key
      || 'this consent';
    confirmAction({
      title: 'Delete consent?',
      message:
        `This will remove the "${title}" consent from this admission. ` +
        `The action is reversible only by the clinic admin (a soft-delete ` +
        `record is kept for audit). Continue only if it was generated by mistake.`,
      confirmText: 'Delete',
      destructive: true,
      onConfirm: async () => {
        setDeletingId(c.consent_id);
        try {
          await api.delete(`/surgical-consents/${c.consent_id}`);
          // Optimistic local removal — keeps the UI snappy
          // even if the parent admission-detail does a slow
          // background reload.
          setConsents((prev) => prev.filter((x) => x.consent_id !== c.consent_id));
          toast.success('Consent deleted.');
        } catch (e: any) {
          const msg =
            (e?.response?.data && typeof e.response.data === 'object' && e.response.data.detail) ||
            e?.message ||
            'Could not delete consent.';
          toast.error(typeof msg === 'string' ? msg : 'Could not delete consent.');
        } finally {
          setDeletingId(null);
        }
      },
    });
  };

  return (
    <View>
      <View style={styles.detCard}>
        <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 8 }}>
          <Text style={styles.subTitle}>Linked Consents</Text>
          <View style={{ flex: 1 }} />
          {!isDischarged ? (
            <TouchableOpacity
              style={styles.smallPrimaryBtn}
              onPress={() => {
                const p = new URLSearchParams();
                p.set('admission_id', admissionId);
                if (a.patient_name) p.set('patient_name', a.patient_name);
                if (a.patient_phone) p.set('patient_phone', a.patient_phone);
                if (a.patient_age) p.set('patient_age', String(a.patient_age));
                if (a.patient_sex) p.set('patient_sex', a.patient_sex);
                onClose();
                setTimeout(() => router.push(`/consents/new?${p.toString()}` as any), 60);
              }}
              testID="ipd-consents-add"
            >
              <Ionicons name="add" size={14} color="#fff" />
              <Text style={styles.smallPrimaryBtnText}>New</Text>
            </TouchableOpacity>
          ) : null}
        </View>
        {consents.length === 0 ? (
          <Text style={styles.noteText}>
            No consents linked yet. Tap "New" or use the
            "Take Consent" action on this admission.
          </Text>
        ) : (
          consents.map((c) => {
            const isDeleting = deletingId === c.consent_id;
            return (
              <View
                key={c.consent_id}
                style={[styles.consentRow, isDeleting && { opacity: 0.5 }]}
                testID={`ipd-consent-${c.consent_id}`}
              >
                <TouchableOpacity
                  style={[styles.consentIcon, { backgroundColor: '#0E7C8B22' }]}
                  onPress={() => {
                    if (isDeleting) return;
                    onClose();
                    setTimeout(() => router.push(`/consents/${c.consent_id}` as any), 60);
                  }}
                  disabled={isDeleting}
                >
                  <Ionicons name="document-text" size={18} color="#0E7C8B" />
                </TouchableOpacity>
                <TouchableOpacity
                  style={{ flex: 1, paddingVertical: 4 }}
                  onPress={() => {
                    if (isDeleting) return;
                    onClose();
                    setTimeout(() => router.push(`/consents/${c.consent_id}` as any), 60);
                  }}
                  disabled={isDeleting}
                >
                  <Text style={styles.consentTitle} numberOfLines={1}>
                    {c.procedure_snapshot?.name?.en
                      || c.procedure_snapshots?.[0]?.name?.en
                      || c.procedure_key}
                  </Text>
                  <Text style={styles.consentSub}>
                    {(c.language || 'en').toUpperCase()}
                    {c.witness_name ? ` · Witness: ${c.witness_name}` : ''}
                    {c.patient_signature_b64 ? ' · ✓ Patient' : ''}
                    {c.doctor_signature_b64 ? ' · ✓ Doctor' : ''}
                    {' · '}{formatISTShort(c.created_at)}
                  </Text>
                </TouchableOpacity>
                {/* Delete (soft) — hidden on already-discharged
                    admissions because once the chart is closed the
                    record is part of the legal IPD file and must
                    only be amended via the clinic admin. */}
                {!isDischarged ? (
                  <TouchableOpacity
                    onPress={() => onDelete(c)}
                    disabled={isDeleting}
                    style={{
                      width: 36,
                      height: 36,
                      borderRadius: 18,
                      alignItems: 'center',
                      justifyContent: 'center',
                      marginRight: 2,
                    }}
                    accessibilityLabel="Delete consent"
                    testID={`ipd-consent-delete-${c.consent_id}`}
                    hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                  >
                    {isDeleting ? (
                      <ActivityIndicator size="small" color={COLORS.danger || '#D14343'} />
                    ) : (
                      <Ionicons name="trash-outline" size={18} color={COLORS.danger || '#D14343'} />
                    )}
                  </TouchableOpacity>
                ) : null}
                <Ionicons name="chevron-forward" size={18} color={COLORS.textSecondary} />
              </View>
            );
          })
        )}
      </View>
    </View>
  );
}
