"""
Backend test for Dashboard Access permission control.

Endpoints under test:
  - GET   /api/me/tier                                              (default rule)
  - GET   /api/admin/primary-owners                                 (new field)
  - PATCH /api/admin/primary-owners/{user_id}/dashboard-perm        (super_owner only)

Re-runnable. All test fixtures cleaned up at teardown.
"""

import os
import sys
import time
import uuid
import subprocess
import requests

BASE = os.environ.get("BACKEND_URL", "http://localhost:8001")
API = f"{BASE}/api"
DB_NAME = "consulturo"

OWNER_TOKEN = "test_session_1776770314741"   # primary_owner sagar
DOCTOR_TOKEN = "test_doc_1776771431524"      # doctor

SUPER_OWNER_EMAIL = "app.consulturo@gmail.com"
SO_USER_ID = f"test-so-dash-{int(time.time())}"
SO_TOKEN = f"test_so_dash_{int(time.time())}"

PASS = []
FAIL = []


def chk(name, cond, detail=""):
    if cond:
        PASS.append(name)
        print(f"  PASS  {name}")
    else:
        FAIL.append((name, detail))
        print(f"  FAIL  {name}  -- {detail}")


def H(token=None):
    h = {"Content-Type": "application/json"}
    if token:
        h["Authorization"] = f"Bearer {token}"
    return h


def mongo(js):
    out = subprocess.run(
        ["mongosh", DB_NAME, "--quiet", "--eval", js],
        capture_output=True, text=True, check=False, timeout=30,
    )
    if out.returncode != 0:
        print("mongosh error:", out.stderr)
    return (out.stdout or "").strip()


# ───────────────────────────────────────────────────────────────────
# Setup / Teardown
# ───────────────────────────────────────────────────────────────────


def seed_super_owner():
    js = f"""
db.users.updateOne(
  {{ user_id: "{SO_USER_ID}" }},
  {{ $set: {{
    user_id: "{SO_USER_ID}",
    email: "{SUPER_OWNER_EMAIL}",
    name: "SO Dash Test",
    role: "super_owner",
    phone: "+9100000000",
    consent_medical: true,
    consent_terms: true,
    consent_at: new Date(),
    created_at: new Date(),
  }} }},
  {{ upsert: true }}
);
db.user_sessions.updateOne(
  {{ session_token: "{SO_TOKEN}" }},
  {{ $set: {{
    session_token: "{SO_TOKEN}",
    user_id: "{SO_USER_ID}",
    expires_at: new Date(Date.now() + 7*24*3600*1000),
    created_at: new Date(),
  }} }},
  {{ upsert: true }}
);
print("seed_so_ok");
"""
    out = mongo(js)
    return "seed_so_ok" in out


def get_sagar_user_id():
    out = mongo(
        "var u=db.users.findOne({email:'sagar.joshi133@gmail.com'});"
        "print(u && u.user_id ? u.user_id : '');"
    )
    return out.strip().splitlines()[-1] if out else ""


def get_doctor_user_id():
    out = mongo(
        f"var s=db.user_sessions.findOne({{session_token:'{DOCTOR_TOKEN}'}});"
        "print(s && s.user_id ? s.user_id : '');"
    )
    return out.strip().splitlines()[-1] if out else ""


def cleanup():
    js = f"""
db.users.deleteOne({{ user_id: "{SO_USER_ID}" }});
db.user_sessions.deleteOne({{ session_token: "{SO_TOKEN}" }});

// Reset sagar's dashboard_full_access to undefined
db.users.updateOne(
  {{ email: "sagar.joshi133@gmail.com" }},
  {{ $unset: {{ dashboard_full_access: "" }} }}
);
db.team_invites.updateMany(
  {{ email: "sagar.joshi133@gmail.com" }},
  {{ $unset: {{ dashboard_full_access: "" }} }}
);

// Delete dashboard_perm_change audit rows generated by the test
db.audit_log.deleteMany({{
  kind: "dashboard_perm_change",
  target_email: "sagar.joshi133@gmail.com"
}});

print("cleanup_ok");
"""
    out = mongo(js)
    return "cleanup_ok" in out


# ───────────────────────────────────────────────────────────────────
# TEST 1: Default dashboard_full_access for owner-tier roles
# ───────────────────────────────────────────────────────────────────


def test_1_defaults():
    print("\n=== Test 1: /api/me/tier defaults ===")

    # 1.1 sagar (primary_owner, no DB flag) → true (default-true rule)
    r = requests.get(f"{API}/me/tier", headers=H(OWNER_TOKEN), timeout=15)
    chk("1.1 sagar /me/tier returns 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    body = r.json() if r.status_code == 200 else {}
    chk("1.1 sagar role=primary_owner", body.get("role") == "primary_owner", f"body={body}")
    chk("1.1 sagar dashboard_full_access default-true",
        body.get("dashboard_full_access") is True,
        f"got={body.get('dashboard_full_access')!r}")

    # 1.2 super_owner → true
    r = requests.get(f"{API}/me/tier", headers=H(SO_TOKEN), timeout=15)
    chk("1.2 super_owner /me/tier 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    body = r.json() if r.status_code == 200 else {}
    chk("1.2 super_owner role=super_owner", body.get("role") == "super_owner", f"body={body}")
    chk("1.2 super_owner is_super_owner=true", body.get("is_super_owner") is True, f"body={body}")
    chk("1.2 super_owner dashboard_full_access=true",
        body.get("dashboard_full_access") is True,
        f"got={body.get('dashboard_full_access')!r}")

    # 1.3 doctor → false (non owner-tier, per-user prop unset)
    r = requests.get(f"{API}/me/tier", headers=H(DOCTOR_TOKEN), timeout=15)
    chk("1.3 doctor /me/tier 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    body = r.json() if r.status_code == 200 else {}
    chk("1.3 doctor role=doctor", body.get("role") == "doctor", f"body={body}")
    chk("1.3 doctor dashboard_full_access=false",
        body.get("dashboard_full_access") is False,
        f"got={body.get('dashboard_full_access')!r}")


# ───────────────────────────────────────────────────────────────────
# TEST 2: Listing endpoint includes new field
# ───────────────────────────────────────────────────────────────────


def test_2_list_includes_field(sagar_uid):
    print("\n=== Test 2: GET /api/admin/primary-owners includes dashboard_full_access ===")
    r = requests.get(f"{API}/admin/primary-owners", headers=H(SO_TOKEN), timeout=15)
    chk("2.1 list returns 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    items = (r.json() or {}).get("items", []) if r.status_code == 200 else []
    chk("2.1 list non-empty", len(items) >= 1, f"len={len(items)}")
    chk("2.1 every row has dashboard_full_access",
        all("dashboard_full_access" in it for it in items),
        f"sample={items[:1]}")
    sagar_row = next((it for it in items if it.get("user_id") == sagar_uid), None)
    chk("2.1 sagar row found", sagar_row is not None, f"items={items}")
    if sagar_row:
        chk("2.1 sagar dashboard_full_access=true (default)",
            sagar_row.get("dashboard_full_access") is True,
            f"row={sagar_row}")


# ───────────────────────────────────────────────────────────────────
# TEST 3: PATCH dashboard-perm endpoint
# ───────────────────────────────────────────────────────────────────


def test_3_patch_lifecycle(sagar_uid):
    print("\n=== Test 3: PATCH /api/admin/primary-owners/{id}/dashboard-perm ===")

    # 5. Flip OFF
    r = requests.patch(
        f"{API}/admin/primary-owners/{sagar_uid}/dashboard-perm",
        headers=H(SO_TOKEN), json={"dashboard_full_access": False}, timeout=15,
    )
    chk("3.5 PATCH false returns 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    body = r.json() if r.status_code == 200 else {}
    chk("3.5 response dashboard_full_access=false",
        body.get("dashboard_full_access") is False, f"body={body}")

    # 6. /me/tier reflects false
    r = requests.get(f"{API}/me/tier", headers=H(OWNER_TOKEN), timeout=15)
    body = r.json() if r.status_code == 200 else {}
    chk("3.6 sagar /me/tier dashboard_full_access=false",
        body.get("dashboard_full_access") is False, f"body={body}")

    # 7. List shows false for sagar
    r = requests.get(f"{API}/admin/primary-owners", headers=H(SO_TOKEN), timeout=15)
    items = (r.json() or {}).get("items", []) if r.status_code == 200 else []
    sagar_row = next((it for it in items if it.get("user_id") == sagar_uid), None)
    chk("3.7 list now sagar dashboard_full_access=false",
        sagar_row is not None and sagar_row.get("dashboard_full_access") is False,
        f"row={sagar_row}")

    # 8. Flip back ON
    r = requests.patch(
        f"{API}/admin/primary-owners/{sagar_uid}/dashboard-perm",
        headers=H(SO_TOKEN), json={"dashboard_full_access": True}, timeout=15,
    )
    chk("3.8 PATCH true returns 200", r.status_code == 200, f"st={r.status_code} body={r.text[:300]}")
    body = r.json() if r.status_code == 200 else {}
    chk("3.8 response dashboard_full_access=true",
        body.get("dashboard_full_access") is True, f"body={body}")

    # 9. /me/tier reflects true
    r = requests.get(f"{API}/me/tier", headers=H(OWNER_TOKEN), timeout=15)
    body = r.json() if r.status_code == 200 else {}
    chk("3.9 sagar /me/tier dashboard_full_access=true",
        body.get("dashboard_full_access") is True, f"body={body}")


# ───────────────────────────────────────────────────────────────────
# TEST 4: Authorization
# ───────────────────────────────────────────────────────────────────


def test_4_authorization(sagar_uid, doctor_uid):
    print("\n=== Test 4: Authorization on PATCH dashboard-perm ===")

    # 10. primary_owner (sagar) → 403
    r = requests.patch(
        f"{API}/admin/primary-owners/{sagar_uid}/dashboard-perm",
        headers=H(OWNER_TOKEN), json={"dashboard_full_access": False}, timeout=15,
    )
    chk("4.10 sagar PATCH → 403", r.status_code == 403, f"st={r.status_code} body={r.text[:300]}")

    # 11. doctor → 403
    r = requests.patch(
        f"{API}/admin/primary-owners/{sagar_uid}/dashboard-perm",
        headers=H(DOCTOR_TOKEN), json={"dashboard_full_access": False}, timeout=15,
    )
    chk("4.11 doctor PATCH → 403", r.status_code == 403, f"st={r.status_code} body={r.text[:300]}")

    # 12. PATCH on a non-primary_owner target → 400
    if doctor_uid:
        r = requests.patch(
            f"{API}/admin/primary-owners/{doctor_uid}/dashboard-perm",
            headers=H(SO_TOKEN), json={"dashboard_full_access": False}, timeout=15,
        )
        chk("4.12 PATCH non-primary_owner target → 400",
            r.status_code == 400, f"st={r.status_code} body={r.text[:300]}")
        if r.status_code == 400:
            detail = (r.json() or {}).get("detail", "")
            chk("4.12 detail mentions primary_owner",
                "primary_owner" in detail.lower() or "primary owner" in detail.lower(),
                f"detail={detail!r}")
    else:
        chk("4.12 (skipped) doctor uid not resolvable", False, "doctor uid empty")

    # 13. PATCH on non-existent user → 404
    r = requests.patch(
        f"{API}/admin/primary-owners/does_not_exist_user_xyz/dashboard-perm",
        headers=H(SO_TOKEN), json={"dashboard_full_access": False}, timeout=15,
    )
    chk("4.13 PATCH unknown user_id → 404", r.status_code == 404, f"st={r.status_code} body={r.text[:300]}")


# ───────────────────────────────────────────────────────────────────
# TEST 5: Audit log
# ───────────────────────────────────────────────────────────────────


def test_5_audit_log():
    print("\n=== Test 5: Audit log entries ===")
    out = mongo(
        "print(db.audit_log.countDocuments({"
        "kind:'dashboard_perm_change',"
        "target_email:'sagar.joshi133@gmail.com'"
        "}));"
    )
    try:
        cnt = int(out.splitlines()[-1])
    except Exception:
        cnt = -1
    chk("5.1 audit_log has >=2 dashboard_perm_change rows for sagar",
        cnt >= 2, f"count={cnt}")

    # Verify shape of latest 2 rows: target_email + new_value present
    out = mongo(
        "var rows=db.audit_log.find({"
        "kind:'dashboard_perm_change',"
        "target_email:'sagar.joshi133@gmail.com'"
        "}).sort({ts:-1}).limit(2).toArray();"
        "print('count='+rows.length);"
        "rows.forEach(function(r){"
        "print('row te='+(r.target_email||'')+' nv='+r.new_value);"
        "});"
    )
    print(f"  audit rows: {out}")
    chk("5.2 audit rows include target_email + new_value",
        ("te=sagar.joshi133@gmail.com" in out) and ("nv=true" in out) and ("nv=false" in out),
        f"out={out}")


# ───────────────────────────────────────────────────────────────────
# TEST 6: Smoke regression — /api/health
# ───────────────────────────────────────────────────────────────────


def test_6_smoke():
    print("\n=== Test 6: Smoke ===")
    r = requests.get(f"{API}/health", timeout=15)
    chk("6.1 /api/health 200", r.status_code == 200, f"st={r.status_code}")
    body = r.json() if r.status_code == 200 else {}
    chk("6.1 /api/health ok=true", body.get("ok") is True, f"body={body}")


# ───────────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────────


def main():
    print(f"Testing against {API}")
    if not seed_super_owner():
        print("FATAL: could not seed super_owner via mongosh")
        sys.exit(2)

    sagar_uid = get_sagar_user_id()
    doctor_uid = get_doctor_user_id()
    print(f"sagar_uid={sagar_uid!r} doctor_uid={doctor_uid!r}")
    if not sagar_uid:
        print("FATAL: could not resolve sagar's user_id")
        cleanup()
        sys.exit(2)

    try:
        test_1_defaults()
        test_2_list_includes_field(sagar_uid)
        test_3_patch_lifecycle(sagar_uid)
        test_4_authorization(sagar_uid, doctor_uid)
        test_5_audit_log()
        test_6_smoke()
    finally:
        print("\n--- cleanup ---")
        cleanup()
        # Sanity confirm
        out = mongo(
            "var u=db.users.findOne({email:'sagar.joshi133@gmail.com'});"
            "print('post_dfa='+u.dashboard_full_access);"
            "print('audit_left='+db.audit_log.countDocuments({"
            "kind:'dashboard_perm_change',"
            "target_email:'sagar.joshi133@gmail.com'}));"
            "print('so_users='+db.users.countDocuments({user_id:'" + SO_USER_ID + "'}));"
            "print('so_sess='+db.user_sessions.countDocuments({session_token:'" + SO_TOKEN + "'}));"
        )
        print(out)

    print(f"\n==== RESULTS: {len(PASS)} PASS, {len(FAIL)} FAIL ====")
    if FAIL:
        for n, d in FAIL:
            print(f"  FAIL  {n}\n        {d}")
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
