"""Pydantic request/response models for the ConsultUro backend.

Auto-extracted from server.py by /tmp/extract_models.py — DO NOT
hand-edit blindly: keep the structure flat-import-friendly so server.py
can do `from models import *`.

Classes are listed in the order they appeared in server.py.
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, EmailStr

class BookingCreate(BaseModel):
    patient_name: str
    patient_phone: str
    # International calling code stored separately so the WhatsApp / Call
    # deep-links always compose a valid E.164 number. Defaults to India.
    country_code: Optional[str] = "+91"
    patient_age: Optional[int] = None
    patient_gender: Optional[str] = None
    reason: str
    booking_date: str
    booking_time: str
    mode: str = "in-person"
    registration_no: Optional[str] = None

class IpssEntry(BaseModel):
    question: str
    score: int

class IpssSubmission(BaseModel):
    entries: List[IpssEntry]
    total_score: int
    severity: str
    qol_score: Optional[int] = None

class PrescriptionMedicine(BaseModel):
    name: str
    dosage: str
    frequency: str
    duration: str
    instructions: Optional[str] = ""
    timing: Optional[str] = ""

class PrescriptionCreate(BaseModel):
    patient_name: str
    patient_age: Optional[int] = None
    patient_gender: Optional[str] = None
    patient_phone: Optional[str] = None
    patient_address: Optional[str] = None
    registration_no: Optional[str] = None
    ref_doctor: Optional[str] = None
    visit_date: str
    chief_complaints: str = ""
    vitals: Optional[str] = ""        # legacy single-line field — preserved
    vitals_pulse: Optional[str] = ""  # e.g. "76/min"
    vitals_bp: Optional[str] = ""     # e.g. "120/80 mmHg"
    ipss_recent: Optional[str] = ""   # e.g. "12 / 35 (moderate)" or freeform
    # Examination subsections (urology-specific)
    exam_pa: Optional[str] = ""           # Per Abdomen
    exam_ext_genitalia: Optional[str] = ""
    exam_eum: Optional[str] = ""          # External Urinary Meatus
    exam_testis: Optional[str] = ""
    exam_dre: Optional[str] = ""          # Digital Rectal Examination
    # Investigation findings — split per modality
    investigation_findings: Optional[str] = ""  # legacy free text
    inv_blood: Optional[str] = ""
    inv_psa: Optional[str] = ""
    inv_usg: Optional[str] = ""
    inv_uroflowmetry: Optional[str] = ""
    inv_ct: Optional[str] = ""
    inv_mri: Optional[str] = ""
    inv_pet: Optional[str] = ""
    investigations_advised: Optional[str] = ""
    diagnosis: Optional[str] = ""
    medicines: List[PrescriptionMedicine] = []
    advice: Optional[str] = ""
    follow_up: Optional[str] = ""
    # Workflow status — staff (reception/nursing/assistant) may save a
    # `draft` consultation containing only patient/vitals/complaints/IPSS;
    # the doctor later resumes and finalises it as a `final` Rx.
    status: Optional[str] = "final"  # draft | final
    # Traceability: links this Rx back to the booking it was started from.
    # Set by the "Start Consultation" workflow from a confirmed booking so
    # the whole patient journey stays linked (booking → consult → Rx).
    source_booking_id: Optional[str] = None

class SessionExchangeBody(BaseModel):
    session_id: str
    # Optional one-time-use handoff id generated by the native app before
    # opening the OAuth browser. The bridge HTML forwards it here so the
    # native app can poll GET /api/auth/handoff/{id} to retrieve the
    # finished session — bypassing flaky Chrome Custom Tabs deep-links.
    handoff_id: Optional[str] = None

class TeamInviteBody(BaseModel):
    email: EmailStr
    name: Optional[str] = None
    role: str
    can_approve_bookings: bool = False
    can_approve_broadcasts: bool = False
    can_send_personal_messages: bool = False
    # Per-user prescriber gate. False by default — only owner-tier
    # users (primary_owner / partner / super_owner) get prescriber
    # rights automatically; everyone else (doctor / nursing /
    # reception / custom) must be explicitly enabled.
    can_prescribe: bool = False
    # Independent gates split out from `can_prescribe` so a clinic
    # can grant e.g. surgery-logbook access without giving Rx rights.
    can_manage_surgeries: bool = False
    can_manage_availability: bool = False

class TeamUpdateBody(BaseModel):
    role: Optional[str] = None
    can_approve_bookings: Optional[bool] = None
    can_approve_broadcasts: Optional[bool] = None
    can_send_personal_messages: Optional[bool] = None
    can_prescribe: Optional[bool] = None
    can_manage_surgeries: Optional[bool] = None
    can_manage_availability: Optional[bool] = None
    dashboard_full_access: Optional[bool] = None
    # When `dashboard_full_access` is False, owner can pick a SUBSET of
    # dashboard tab ids (e.g. ["bookings", "rx"]) the team member is
    # allowed to see. Null/empty list ⇒ no extra tabs (default).
    dashboard_tabs: Optional[List[str]] = None

class RoleLabelBody(BaseModel):
    label: str
    # Optional category to derive permissions: "clinical" (doctor-level) | "staff" | "patient"
    category: str = "staff"

class HomepageSettingsBody(BaseModel):
    doctor_photo_url: Optional[str] = None
    cover_photo_url: Optional[str] = None
    doctor_name: Optional[str] = None  # display name shown on home hero (e.g. "Dr. Sagar Joshi")
    tagline: Optional[str] = None
    clinic_name: Optional[str] = None
    clinic_address: Optional[str] = None
    clinic_phone: Optional[str] = None
    doctor_degrees: Optional[str] = None
    doctor_reg_no: Optional[str] = None
    signature_url: Optional[str] = None  # owner digital signature (rendered on Rx PDFs)
    # --- Added for in-app Help/Contact screen ---
    clinic_whatsapp: Optional[str] = None  # e.g. +918155075669
    clinic_email: Optional[str] = None  # support email
    clinic_map_url: Optional[str] = None  # Google Maps deep link
    clinic_hours: Optional[str] = None  # freeform string e.g. "Mon–Sat 8am–8pm"
    emergency_note: Optional[str] = None  # e.g. "Emergency on Sundays"

class ReferrerBody(BaseModel):
    name: str
    phone: Optional[str] = ""
    whatsapp: Optional[str] = ""
    email: Optional[str] = ""
    clinic: Optional[str] = ""
    speciality: Optional[str] = ""
    city: Optional[str] = ""
    notes: Optional[str] = ""

class BookingStatusBody(BaseModel):
    status: Optional[str] = None  # confirmed | completed | cancelled | rejected
    booking_date: Optional[str] = None
    booking_time: Optional[str] = None
    note: Optional[str] = ""
    # Free-text reason captured when staff rejects, cancels (staff-initiated),
    # or reschedules a booking. Shown to the patient on their booking card
    # and included in the in-app notification body.
    reason: Optional[str] = None
    # Private clinical note attached by the doctor. NOT shown to the patient
    # and NOT included in the Rx PDF — used only on the dashboard's
    # Consultations tab for doctor's own recall.
    doctor_note: Optional[str] = None

class PatientCancelBody(BaseModel):
    """Patient-initiated cancellation. `patient_phone` is required when the
    caller is unauthenticated (guest booking) as a lightweight ownership
    check. Reason is mandatory so staff can understand the no-show pattern."""
    reason: str
    patient_phone: Optional[str] = None

class SurgeryBody(BaseModel):
    patient_phone: str
    patient_name: str
    patient_age: Optional[int] = None
    patient_sex: Optional[str] = None
    patient_id_ipno: Optional[str] = ""
    registration_no: Optional[str] = ""
    address: Optional[str] = ""
    patient_category: Optional[str] = ""  # Regular / Insurance / Charity etc.
    consultation_date: Optional[str] = ""
    referred_by: Optional[str] = ""
    clinical_examination: Optional[str] = ""
    diagnosis: Optional[str] = ""
    imaging: Optional[str] = ""
    department: Optional[str] = ""  # OPD / IPD
    date_of_admission: Optional[str] = ""
    surgery_name: str
    date: str  # Date of Surgery/Procedure
    hospital: Optional[str] = ""
    operative_findings: Optional[str] = ""
    post_op_investigations: Optional[str] = ""
    date_of_discharge: Optional[str] = ""
    follow_up: Optional[str] = ""
    notes: Optional[str] = ""

class BlogPostBody(BaseModel):
    title: str
    category: Optional[str] = "Urology"
    excerpt: Optional[str] = ""
    content: str  # plain text or light HTML
    cover: Optional[str] = ""  # URL or base64 data URI
    published: bool = True  # legacy; kept for backward compat
    status: Optional[str] = None  # draft | pending_review | published | rejected

class BlogReviewBody(BaseModel):
    status: str  # pending_review | published | rejected | draft
    review_note: Optional[str] = ""

class AvailabilitySlot(BaseModel):
    start: str  # HH:MM
    end: str  # HH:MM

class DayAvailabilityBody(BaseModel):
    # Each day key: 'mon', 'tue', ..., 'sun'
    mon_in: List[AvailabilitySlot] = []
    tue_in: List[AvailabilitySlot] = []
    wed_in: List[AvailabilitySlot] = []
    thu_in: List[AvailabilitySlot] = []
    fri_in: List[AvailabilitySlot] = []
    sat_in: List[AvailabilitySlot] = []
    sun_in: List[AvailabilitySlot] = []
    mon_on: List[AvailabilitySlot] = []
    tue_on: List[AvailabilitySlot] = []
    wed_on: List[AvailabilitySlot] = []
    thu_on: List[AvailabilitySlot] = []
    fri_on: List[AvailabilitySlot] = []
    sat_on: List[AvailabilitySlot] = []
    sun_on: List[AvailabilitySlot] = []
    # days the doctor is fully unavailable (e.g. Sunday)
    off_days: List[str] = []  # ['sun', 'sat']
    note: Optional[str] = ""

class HandoffInitBody(BaseModel):
    handoff_id: Optional[str] = None  # client-provided UUID (preferred)

class MagicRequestBody(BaseModel):
    email: EmailStr

class MagicExchangeBody(BaseModel):
    token: str

class OtpRequestBody(BaseModel):
    email: EmailStr

class OtpVerifyBody(BaseModel):
    email: EmailStr
    code: str

class FirebasePhoneVerifyBody(BaseModel):
    id_token: str
    email: Optional[EmailStr] = None  # required for first-time signups

class LinkPhoneBody(BaseModel):
    id_token: str  # Firebase phone-auth token

class LinkEmailBody(BaseModel):
    email: EmailStr

class LinkEmailVerifyBody(BaseModel):
    email: EmailStr
    code: str

class RenderPdfBody(BaseModel):
    html: str
    filename: Optional[str] = None

class MyProfileBody(BaseModel):
    phone: Optional[str] = None

class UnavailabilityBody(BaseModel):
    date: Optional[str] = None       # YYYY-MM-DD (omitted for recurring rules)
    all_day: bool = True
    start_time: Optional[str] = None  # "HH:MM" (24h)
    end_time: Optional[str] = None
    recurring_weekly: bool = False
    day_of_week: Optional[int] = None  # 0..6 (Mon..Sun); inferred from date if missing
    reason: Optional[str] = None

class ToolScoreBody(BaseModel):
    tool_id: str
    score: Optional[float] = None
    label: Optional[str] = None  # Human-readable summary (e.g. "Moderate 13/35")
    details: Optional[Dict[str, Any]] = None  # Inputs + derived numbers

class BladderEntryBody(BaseModel):
    date: str  # YYYY-MM-DD
    time: str  # HH:mm (24h)
    volume_ml: Optional[int] = None  # null allowed if only leak entry
    fluid_intake_ml: Optional[int] = None
    urgency: Optional[int] = None  # 0..4
    leak: Optional[bool] = False
    note: Optional[str] = None

class PushRegisterBody(BaseModel):
    token: str
    platform: Optional[str] = None
    device_name: Optional[str] = None

class BroadcastCreate(BaseModel):
    title: str
    body: str
    image_url: Optional[str] = None
    link: Optional[str] = None
    target: Optional[str] = "all"  # all | patients | staff

class BroadcastReview(BaseModel):
    action: str  # approve | reject
    reject_reason: Optional[str] = None

class MessageAttachment(BaseModel):
    """Base64-encoded attachment for personal messages.
    Mime is required; size is bytes (best-effort, the server
    re-validates from the data URI). The client sends `data_url` in
    the form `data:<mime>;base64,<...>` so we can persist raw and
    render it back without a separate upload endpoint.
    """
    name: str
    mime: str
    size_bytes: Optional[int] = 0
    data_url: str
    kind: Optional[str] = None  # "image" | "video" | "file" — hint for renderer

class PersonalMessageBody(BaseModel):
    recipient_user_id: Optional[str] = None
    recipient_email: Optional[EmailStr] = None
    title: str
    body: str
    attachments: Optional[List[MessageAttachment]] = None

class MessagingPermissionBody(BaseModel):
    allowed: bool

class PromoteByEmailBody(BaseModel):
    email: str

class BlogPermBody(BaseModel):
    can_create_blog: bool

class DashboardPermBody(BaseModel):
    dashboard_full_access: bool

class SuspendBody(BaseModel):
    suspended: bool
    reason: Optional[str] = None

class ConsentBody(BaseModel):
    data_consent: bool = False         # consent to medical-data storage
    policy_consent: bool = False       # agrees to Privacy + Terms
    marketing_consent: bool = False    # optional — reminders via WA/SMS

class PatientRegManual(BaseModel):
    phone: str
    registration_no: str
    name: Optional[str] = None

class NoteBody(BaseModel):
    title: Optional[str] = ""
    body: str
    # ISO datetime string (UTC) at which the user wants to be reminded.
    # Null = no reminder. Stored as datetime in Mongo.
    reminder_at: Optional[str] = None
    # Free-text chip labels (max 12, each <=24 chars).
    labels: Optional[List[str]] = None

class MedicineCustomBody(BaseModel):
    name: str
    generic: Optional[str] = ""
    category: Optional[str] = "Other"
    dosage: Optional[str] = ""
    frequency: Optional[str] = ""
    duration: Optional[str] = ""
    timing: Optional[str] = ""
    instructions: Optional[str] = ""

class ProstateVolumeBody(BaseModel):
    volume_ml: float
    source: Optional[str] = None  # USG / MRI / DRE / Other
    measured_on: Optional[str] = None  # YYYY-MM-DD; defaults to today
    notes: Optional[str] = ""

class ClinicSettingsPatch(BaseModel):
    """All fields optional — only provided keys are written. Free-text
    fields are length-capped to keep documents reasonable.
    """
    main_photo_url: Optional[str] = None     # data: URI or external URL
    cover_photo_url: Optional[str] = None
    # Letterhead — banner image that REPLACES the entire app-logo +
    # clinic-name + contact strip at the top of every Rx PDF page when
    # `use_letterhead` is True. Stored inline as a data: URI to match
    # main_photo_url's pattern. Capped at ~2 MB on write.
    letterhead_image_b64: Optional[str] = None
    use_letterhead: Optional[bool] = None
    # Per-clinic editable copy that flows into the prescription PDF —
    # "Patient Education" tips card and the "Need Help?" mini-card. Both
    # accept simple HTML (sanitised at render time). When null/empty,
    # the renderer falls back to the built-in defaults.
    patient_education_html: Optional[str] = None
    need_help_html: Optional[str] = None
    doctor_name: Optional[str] = None        # e.g. "Dr Ajay Mehta"
    doctor_title: Optional[str] = None       # e.g. "Consultant Urologist"
    doctor_tagline: Optional[str] = None
    doctor_short_bio: Optional[str] = None
    clinic_name: Optional[str] = None
    clinic_website: Optional[str] = None
    social_facebook: Optional[str] = None
    social_instagram: Optional[str] = None
    social_twitter: Optional[str] = None
    social_linkedin: Optional[str] = None
    social_youtube: Optional[str] = None
    social_whatsapp: Optional[str] = None
    external_blog_links: Optional[List[Dict[str, str]]] = None  # [{title,url}]
    # Partner-permission toggles (controlled by primary_owner only).
    # `partner_can_edit_branding` is the legacy umbrella toggle (still
    # honoured for backwards compat as a fallback). New granular flags
    # below override it on a per-section basis.
    partner_can_edit_branding: Optional[bool] = None
    partner_can_edit_about_doctor: Optional[bool] = None
    partner_can_edit_blog: Optional[bool] = None
    partner_can_edit_videos: Optional[bool] = None
    partner_can_edit_education: Optional[bool] = None
    partner_can_manage_broadcasts: Optional[bool] = None
    # Granular branding sub-toggles (Primary-Owner-only). Default True.
    partner_can_edit_main_photo: Optional[bool] = None
    partner_can_edit_cover_photo: Optional[bool] = None
    partner_can_edit_clinic_info: Optional[bool] = None       # clinic_name + website
    partner_can_edit_socials: Optional[bool] = None           # all social_* handles

class CreateDemoBody(BaseModel):
    email: str
    name: Optional[str] = None
    role: Optional[str] = "primary_owner"  # "primary_owner" or "patient"
    seed_sample_data: Optional[bool] = True  # patient only — pre-fill bookings/Rx/IPSS

