/**
 * Shared dashboard styles — extracted from app/dashboard.tsx during
 * Phase 1 of the 2026-05-25 monolith-shrink refactor so the new
 * panels (BookingsPanel, MonthGrid, future OT / IPD / Consent panels)
 * can reuse the same look without copy-pasting 300+ lines of style
 * tokens.
 *
 * RULE: Keep this file PURE — only StyleSheet.create() output, no
 * conditional logic, no component code. If a style needs theming or
 * responsive variants, layer that in the caller.
 */
import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADIUS } from '../theme';

export const styles = StyleSheet.create({
  hero: { paddingHorizontal: 16, paddingBottom: 4, borderBottomLeftRadius: 22, borderBottomRightRadius: 22 },
  heroDesktop: { paddingHorizontal: 24, paddingBottom: 4, paddingTop: 6, borderBottomLeftRadius: 0, borderBottomRightRadius: 0 },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 6 },
  topActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  backBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { ...FONTS.h4, color: '#fff', fontSize: 16 },
  headerDate: { ...FONTS.body, color: 'rgba(255,255,255,0.85)', fontSize: 11, marginTop: 1 },
  bellBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center' },
  bellBadge: { position: 'absolute', top: -4, right: -4, minWidth: 18, height: 18, paddingHorizontal: 4, borderRadius: 9, backgroundColor: COLORS.accent, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  bellBadgeText: { color: '#fff', ...FONTS.label, fontSize: 10 },
  tabBadge: { position: 'absolute', top: -6, right: -10, minWidth: 16, height: 16, paddingHorizontal: 3, borderRadius: 8, backgroundColor: COLORS.accent, alignItems: 'center', justifyContent: 'center' },
  tabBadgeText: { color: '#fff', ...FONTS.label, fontSize: 9 },
  fabMain: { position: 'absolute', right: 20, bottom: 24, width: 56, height: 56, borderRadius: 28, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center', shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.4, shadowRadius: 10, elevation: 10 },
  fabAction: { position: 'absolute', right: 20, bottom: 84, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 24, backgroundColor: COLORS.primary, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 6 },
  fabActionText: { color: '#fff', ...FONTS.bodyMedium, fontSize: 13 },
  userCard: { flexDirection: 'row', alignItems: 'center', marginTop: 6, backgroundColor: 'rgba(255,255,255,0.14)', borderRadius: 16, padding: 10 },
  heroPhoto: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#fff' },
  heroName: { ...FONTS.h4, color: '#fff', fontSize: 16 },
  heroEmail: { ...FONTS.body, color: '#E0F7FA', fontSize: 12 },
  // Role badge shrunk to ~2/3 of previous size per design feedback —
  // padding, gap, radius and font size all scaled down proportionally.
  heroRole: { flexDirection: 'row', alignItems: 'center', gap: 3, alignSelf: 'flex-start', backgroundColor: '#fff', paddingHorizontal: 5, paddingVertical: 1, borderRadius: 6, maxWidth: '100%' },
  heroRoleText: { ...FONTS.label, color: COLORS.primary, fontSize: 8, letterSpacing: 0.3, flexShrink: 1 },
  // Wraps the primary role badge + the optional Full Access pill so they
  // sit side-by-side rather than stacked. Wraps to a new line gracefully
  // on extra-narrow phones / long role names.
  heroBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 4, marginTop: 4, maxWidth: '100%' },
  // Distinct gold-tinted treatment for "Full Access" so it pops next to
  // the role chip without competing visually with the primary CTA.
  // Scaled proportionally to the shrunken heroRole badge.
  fullAccessBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#F5C26B',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 2,
    elevation: 1,
  },
  fullAccessText: { ...FONTS.label, color: '#5C3D00', fontSize: 7, letterSpacing: 0.3 },
  tabBarContainer: { backgroundColor: COLORS.bg, paddingTop: 4, paddingBottom: 2 },
  tabBarContainerDesktop: { paddingTop: 4, paddingBottom: 2, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  tabBarWrap: { maxHeight: 48 },
  tabBarScroll: { paddingHorizontal: 20, gap: 8, alignItems: 'center' },
  tabBtn: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, paddingVertical: 8, paddingHorizontal: 14, borderRadius: RADIUS.pill, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border, shadowColor: COLORS.primary, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2, minWidth: 90 },
  tabBtnDesktop: { paddingVertical: 7, paddingHorizontal: 12, minWidth: 0, gap: 5 },
  tabBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary, shadowOpacity: 0.22, shadowRadius: 6 },
  tabText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 14 },
  statsRow: { flexDirection: 'row', gap: 6 },
  // Compact colored pill row — replaces stat boxes + status filter chips.
  // Wraps to 2 lines on narrow phones; each pill shows label + count.
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  statusPillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
  },
  statusPillLabel: { ...FONTS.bodyMedium, fontSize: 11 },
  statusPillCount: {
    minWidth: 18,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusPillCountText: { ...FONTS.bodyMedium, fontSize: 10 },
  // ── Filter dropdown (replaces the 6-chip status row) ────────────
  filterDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    marginTop: 4,
  },
  filterDropdownLabel: { ...FONTS.bodyMedium, fontSize: 14, flex: 1 },
  filterDot: { width: 10, height: 10, borderRadius: 5 },
  filterBackdrop: {
    flex: 1,
    backgroundColor: '#0008',
    justifyContent: 'center',
    padding: 24,
  },
  filterSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    maxWidth: 420,
    width: '100%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  filterSheetTitle: { ...FONTS.h4, color: COLORS.textPrimary, marginBottom: 10, marginLeft: 4 },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 10,
    marginBottom: 2,
  },
  filterRowLabel: { flex: 1, fontSize: 14 },
  statBox: { flex: 1, backgroundColor: '#fff', paddingVertical: 8, paddingHorizontal: 6, borderRadius: RADIUS.md, borderLeftWidth: 3, borderWidth: 1, borderColor: COLORS.border, minWidth: 0, alignItems: 'flex-start' },
  statVal: { ...FONTS.h2, fontSize: 18 },
  statLbl: { ...FONTS.label, color: COLORS.textSecondary, fontSize: 10, marginTop: 2, textTransform: 'uppercase', letterSpacing: 0.3 },
  filterChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: RADIUS.pill, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border },
  filterChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  // Quick-jump pills — slimmer than filterChip, sit above viewToggle
  quickJump: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: COLORS.primary + '0F',
    borderWidth: 1,
    borderColor: COLORS.primary + '33',
  },
  quickJumpActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  quickJumpText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 11 },
  smartChip: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: '#fff',
    borderWidth: 1, borderColor: COLORS.primary + '33',
  },
  smartChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  smartChipText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 13 },
  bulkBar: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: COLORS.primary + '0D',
    borderWidth: 1, borderColor: COLORS.primary + '33',
    borderRadius: RADIUS.md,
    paddingVertical: 6, paddingHorizontal: 8,
    marginBottom: 10,
    gap: 6,
  },
  bulkBarText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 12 },
  bulkSelectAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: RADIUS.pill,
    backgroundColor: COLORS.primary + '14',
    borderWidth: 1,
    borderColor: COLORS.primary + '44',
  },
  bulkSelectAllText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 12, minWidth: 20 },
  // Compact icon-only action button (32x32) — fits 3 in the right cluster
  // without overlapping on 360px-wide screens.
  bulkIconBtn: {
    width: 32, height: 32, borderRadius: 16,
    alignItems: 'center', justifyContent: 'center',
  },
  bulkBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 10, paddingVertical: 7, borderRadius: RADIUS.pill,
  },
  bulkBtnText: { ...FONTS.bodyMedium, color: '#fff', fontSize: 12 },
  bulkCheckbox: { marginRight: 10, marginTop: 2 },
  bkCardSelected: { borderColor: COLORS.primary, borderWidth: 2, backgroundColor: COLORS.primary + '08' },
  // Desktop grid container — wraps booking & Rx cards into a 2-up
  // flex grid on wide screens. Mobile keeps the existing single
  // column stack.
  bkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  bkCardDesktop: {
    width: '49.3%',
  },
  filterText: { ...FONTS.body, color: COLORS.textPrimary, fontSize: 13 },
  bkCard: { backgroundColor: '#fff', padding: 10, borderRadius: RADIUS.md, marginBottom: 8, borderWidth: 1, borderColor: COLORS.border },
  approverBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', backgroundColor: COLORS.success + '1A', borderWidth: 1, borderColor: COLORS.success + '40', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, marginTop: 8 },
  approverBadgeText: { ...FONTS.label, color: COLORS.success, fontSize: 11, flexShrink: 1 },
  bkHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  bkName: { ...FONTS.bodyMedium, color: COLORS.textPrimary, fontSize: 16 },
  bkMeta: { ...FONTS.body, color: COLORS.textSecondary, fontSize: 13, marginTop: 2 },
  statusPill: { backgroundColor: COLORS.success + '22', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
  statusText: { ...FONTS.label, color: COLORS.success, fontSize: 11, textTransform: 'uppercase' },
  bkReason: { ...FONTS.body, color: COLORS.textPrimary, marginTop: 6 },
  bkFoot: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, rowGap: 6, marginTop: 10 },
  bkAction: { flexDirection: 'row', alignItems: 'center', gap: 4, maxWidth: '100%' },
  bkActionText: { ...FONTS.body, color: COLORS.primary, fontSize: 13 },
  bkButtons: { flexDirection: 'row', gap: 8, marginTop: 10 },
  bkSmallBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 8, borderRadius: RADIUS.pill, borderWidth: 1, borderColor: COLORS.success, backgroundColor: '#fff' },
  bkSmallText: { ...FONTS.bodyMedium, fontSize: 13 },
  // Item 7 — "Start Consultation / Join Video" CTA. Solid green pill placed
  // above the existing reschedule/cancel row so staff cannot miss it.
  startConsultBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: RADIUS.pill,
    backgroundColor: COLORS.success,
    shadowColor: COLORS.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
    minHeight: 44, // accessibility: thumb-friendly target
  },
  startConsultText: {
    ...FONTS.bodyMedium,
    color: '#FFFFFF',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  startConsultBadge: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 4,
  },
  startConsultBadgeText: {
    ...FONTS.label,
    color: '#FFFFFF',
    fontSize: 11,
  },
  rxCard: { backgroundColor: '#fff', padding: 14, borderRadius: RADIUS.md, marginTop: 10, borderWidth: 1, borderColor: COLORS.border },
  exportBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, height: 40, borderRadius: 24, borderWidth: 1, borderColor: COLORS.primary + '40', backgroundColor: COLORS.primary + '0F' },
  refreshBtn: {
    width: 40, height: 40, borderRadius: 20,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: COLORS.primary + '40',
    backgroundColor: COLORS.primary + '0F',
  },
  iconSquareBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  popupPanel: {
    backgroundColor: '#fff',
    borderRadius: RADIUS.md,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 8,
  },
  popupTitle: { ...FONTS.label, color: COLORS.primary, fontSize: 10, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  exportText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 13 },
  rxActionRow: { flexDirection: 'row', marginTop: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: COLORS.border, justifyContent: 'space-around' },
  rxRowAction: { alignItems: 'center', justifyContent: 'center', flex: 1, paddingVertical: 6, gap: 3 },
  rxRowActionText: { ...FONTS.label, fontSize: 11 },
  sectionTitle: { ...FONTS.h4, color: COLORS.textPrimary, marginBottom: 10 },
  formCard: { backgroundColor: '#fff', padding: 16, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border },
  input: { backgroundColor: COLORS.bg, padding: 12, borderRadius: RADIUS.md, ...FONTS.body, color: COLORS.textPrimary, borderWidth: 1, borderColor: COLORS.border },
  smallLabel: { ...FONTS.label, color: COLORS.textSecondary, marginTop: 12 },
  roleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  roleChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: RADIUS.pill, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border },
  roleText: { ...FONTS.body, color: COLORS.textPrimary, fontSize: 13 },
  note: { ...FONTS.body, color: COLORS.textSecondary, fontSize: 13, marginTop: 10, lineHeight: 19 },
  tmCard: { backgroundColor: '#fff', padding: 12, borderRadius: RADIUS.md, marginBottom: 8, borderWidth: 1, borderColor: COLORS.border },
  permToggle: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    marginTop: 10, paddingTop: 10,
    borderTopWidth: 1, borderTopColor: COLORS.border,
  },
  permToggleOn: {},
  permLabel: { ...FONTS.bodyMedium, color: COLORS.textPrimary, fontSize: 13 },
  permSub: { ...FONTS.body, color: COLORS.textSecondary, fontSize: 11, marginTop: 1 },
  permSwitch: {
    width: 38, height: 22, borderRadius: 11,
    backgroundColor: COLORS.border,
    padding: 2,
    justifyContent: 'center',
  },
  permSwitchOn: { backgroundColor: '#10B981' },
  permKnob: {
    width: 18, height: 18, borderRadius: 9,
    backgroundColor: '#fff',
  },
  permKnobOn: { transform: [{ translateX: 16 }] },
  tmAvatar: { width: 40, height: 40, borderRadius: 20 },
  tmName: { ...FONTS.bodyMedium, color: COLORS.textPrimary, fontSize: 15 },
  tmEmail: { ...FONTS.body, color: COLORS.textSecondary, fontSize: 13 },
  tmTagRow: { flexDirection: 'row', gap: 6, marginTop: 4 },
  tmRole: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8, backgroundColor: COLORS.primary + '18' },
  tmRoleText: { ...FONTS.label, color: COLORS.primary, fontSize: 10 },
  tmStatus: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  tmStatusText: { ...FONTS.label, fontSize: 10 },
  editBox: { marginTop: 10, padding: 12, backgroundColor: COLORS.bg, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border },
  approveRow: { flexDirection: 'row', alignItems: 'flex-start', padding: 12, marginTop: 12, backgroundColor: COLORS.bg, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border },
  approveLbl: { ...FONTS.bodyMedium, color: COLORS.textPrimary, fontSize: 14 },
  approveSub: { ...FONTS.body, color: COLORS.textSecondary, fontSize: 12, marginTop: 2, lineHeight: 17 },
  viewToggle: { flexDirection: 'row', gap: 6, marginTop: 8 },
  viewBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 6, borderRadius: RADIUS.pill, borderWidth: 1, borderColor: COLORS.border, backgroundColor: '#fff' },
  viewBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  viewText: { ...FONTS.bodyMedium, color: COLORS.primary, fontSize: 12 },
  dateNav: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 6 },
  navArrow: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.border },
  dateNavText: { ...FONTS.bodyMedium, color: COLORS.textPrimary, flex: 1, textAlign: 'center' },
  todayBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, backgroundColor: COLORS.primary + '18' },
  todayText: { ...FONTS.label, color: COLORS.primary, fontSize: 10 },
  weekDay: { width: 52, paddingVertical: 8, borderRadius: 10, alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border, position: 'relative' },
  weekDow: { ...FONTS.label, color: COLORS.textSecondary, fontSize: 10 },
  weekDate: { ...FONTS.h4, color: COLORS.textPrimary, fontSize: 18, marginTop: 2 },
  weekDot: { position: 'absolute', top: 6, right: 6, minWidth: 16, height: 16, borderRadius: 8, paddingHorizontal: 4, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  weekDotText: { color: '#fff', fontSize: 9, fontFamily: 'DMSans_700Bold' },
  monthGrid: { marginTop: 10, backgroundColor: '#fff', borderRadius: RADIUS.lg, padding: 10, borderWidth: 1, borderColor: COLORS.border },
  monthRow: { flexDirection: 'row' },
  monthDow: { flex: 1, ...FONTS.label, color: COLORS.textSecondary, textAlign: 'center', fontSize: 10, paddingVertical: 6 },
  monthCell: { flex: 1, aspectRatio: 1, margin: 2, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.bg },
  monthCellOther: { opacity: 0.35 },
  monthCellToday: { backgroundColor: COLORS.primary + '28' },
  monthCellText: { ...FONTS.body, color: COLORS.textPrimary, fontSize: 12 },
  monthCellDot: { position: 'absolute', bottom: 4, minWidth: 14, height: 14, borderRadius: 7, paddingHorizontal: 3, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  monthCellDotText: { color: '#fff', fontSize: 8, fontFamily: 'DMSans_700Bold' },
});
