/**
 * PhrMonthlySummary — Gemini-powered 30-day plain-English summary
 * for the patient. Shown at the top of /my-records overview.
 * Cached server-side for 24h to keep token cost bounded.
 *
 * IpssSparkline — tiny inline trendline of the patient's IPSS
 * scores over time. Sits inside the Scores tab on /my-records.
 */
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, TouchableOpacity, Platform } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import Svg, { Polyline, Circle, Line as SvgLine } from 'react-native-svg';
import api from './api';
import { COLORS, RADIUS } from './theme';

export function PhrMonthlySummary() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<any | null>(null);
  const [expanded, setExpanded] = useState(false);

  const fetchSummary = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/patients/me/phr/monthly-summary');
      setData(data);
    } catch { setData(null); }
    finally { setLoading(false); }
  };

  useEffect(() => { void fetchSummary(); }, []);

  if (loading) {
    return (
      <View style={styles.card}>
        <ActivityIndicator color="#fff" />
      </View>
    );
  }
  if (!data?.summary) return null;

  return (
    <LinearGradient
      colors={['#0d9488', '#0f766e']}
      style={styles.card}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 1 }}
    >
      <View style={styles.headerRow}>
        <View style={styles.aiBadge}>
          <Ionicons name="sparkles" size={14} color="#fff" />
        </View>
        <Text style={styles.headerTitle}>Your last 30 days</Text>
        <TouchableOpacity onPress={fetchSummary} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
          <Ionicons name="refresh" size={14} color="rgba(255,255,255,0.7)" />
        </TouchableOpacity>
      </View>
      <Text style={styles.body} numberOfLines={expanded ? undefined : 3}>
        {data.summary}
      </Text>
      {data.summary && data.summary.length > 160 ? (
        <TouchableOpacity onPress={() => setExpanded(!expanded)}>
          <Text style={styles.expandText}>{expanded ? 'Show less' : 'Read more'}</Text>
        </TouchableOpacity>
      ) : null}
      <Text style={styles.footer}>
        {data.cached ? '✦ Cached' : '✦ Fresh'} · AI-generated by Gemini · {data.period_start} → {data.period_end}
      </Text>
    </LinearGradient>
  );
}

/* ─────────────────────────────────────────────────────────────────
   IpssSparkline — render a small SVG trendline from an array of
   { date, score } points. Designed for the Scores tab card.
───────────────────────────────────────────────────────────────── */
type ScorePoint = { date?: string; score?: number; total_score?: number; created_at?: string };

export function IpssSparkline({ points, width = 220, height = 60 }: { points: ScorePoint[]; width?: number; height?: number }) {
  // Hard guard: render nothing rather than crash if `react-native-svg`
  // failed to load or `points` is malformed. Crashes here were
  // bouncing patients back to the home tab from /my-records.
  try {
    if (!Svg || !Polyline) return null;
  } catch {
    return null;
  }
  if (!Array.isArray(points) || points.length < 2) {
    return (
      <View style={[styles.sparkEmpty, { width, height }]}>
        <Text style={styles.sparkEmptyText}>Not enough data — score over time will appear here.</Text>
      </View>
    );
  }
  const series = points
    .filter((p) => p && typeof p === 'object')
    .map((p) => ({
      ts: String(p.date || p.created_at || ''),
      v: Number(typeof p.total_score === 'number' ? p.total_score : (p.score || 0)) || 0,
    }))
    .filter((p) => p.ts && Number.isFinite(p.v))
    .sort((a, b) => (a.ts > b.ts ? 1 : -1));
  if (series.length < 2) {
    return (
      <View style={[styles.sparkEmpty, { width, height }]}>
        <Text style={styles.sparkEmptyText}>Need at least 2 scores to chart.</Text>
      </View>
    );
  }
  try {
    const min = Math.min(...series.map((s) => s.v));
    const max = Math.max(...series.map((s) => s.v));
    const range = Math.max(1, max - min);
    const pad = 6;
    const W = Math.max(1, width - 2 * pad);
    const H = Math.max(1, height - 2 * pad);
    const pts = series.map((s, i) => {
      const x = pad + (i / Math.max(1, series.length - 1)) * W;
      const y = pad + H - ((s.v - min) / range) * H;
      return [x, y] as const;
    });
    const polylinePts = pts.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
    return (
      <View style={[styles.sparkBox, { width, height }]}>
        <Svg width={width} height={height}>
          <SvgLine x1={pad} y1={height - pad} x2={width - pad} y2={height - pad} stroke="#e2e8f0" strokeWidth={1} />
          <Polyline points={polylinePts} fill="none" stroke="#0d9488" strokeWidth={2} />
          {pts.map(([x, y], i) => (
            <Circle key={i} cx={x} cy={y} r={2.5} fill="#0d9488" />
          ))}
        </Svg>
        <View style={styles.sparkLabels}>
          <Text style={styles.sparkLabel}>{min}</Text>
          <Text style={styles.sparkLabel}>↗ {series[series.length - 1].v}</Text>
        </View>
      </View>
    );
  } catch {
    return null;
  }
}

const styles = StyleSheet.create({
  card: {
    padding: 14,
    borderRadius: RADIUS.card,
    marginBottom: 12,
    ...Platform.select({
      ios: { shadowColor: '#0d9488', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.18, shadowRadius: 12 },
      android: { elevation: 3 },
    }),
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  aiBadge: {
    width: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center', justifyContent: 'center',
  },
  headerTitle: { color: '#fff', fontWeight: '800', fontSize: 14, flex: 1 },
  body: { color: 'rgba(255,255,255,0.95)', fontSize: 13, lineHeight: 19 },
  expandText: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 6, fontWeight: '700' },
  footer: { color: 'rgba(255,255,255,0.6)', fontSize: 10, marginTop: 8 },
  sparkBox: { backgroundColor: '#fff', borderRadius: RADIUS.card, borderWidth: 1, borderColor: COLORS.border, padding: 4, position: 'relative' },
  sparkLabels: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 6, marginTop: -4 },
  sparkLabel: { color: COLORS.textSecondary, fontSize: 9.5, fontWeight: '700' },
  sparkEmpty: { padding: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f8fafc', borderRadius: RADIUS.card, borderWidth: 1, borderColor: COLORS.border },
  sparkEmptyText: { color: COLORS.textTertiary, fontSize: 10.5, textAlign: 'center' },
});
